service: report-generator

provider:
  name: aws 
  runtime: python3.11
  profile: cheorish-admin
  stage: v1
  region: ap-northeast-2
  timeout: 900  # 런팟 콜드스타트 고려해서 15분 (최대값)
  memorySize: 256  # requests만 사용하므로 최소 메모리
  environment:
    FASTAPI_REPORT_CALLBACK_URL: ${env:FASTAPI_REPORT_CALLBACK_URL}
    RUNPOD_API_KEY: ${env:RUNPOD_API_KEY}
    RUNPOD_AGENT_ENDPOINT_ID: ${env:RUNPOD_AGENT_ENDPOINT_ID}
    # SQS 관련 환경변수 추가
    SQS_REPORT_QUEUE_ARN: ${env:SQS_REPORT_QUEUE_ARN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: 
        - ${env:SQS_REPORT_QUEUE_ARN}
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  generateReport:
    handler: generate_report.lambda_handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - sqs:
          arn: ${env:SQS_REPORT_QUEUE_ARN}
          batchSize: 1  # 한 번에 하나씩 처리

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
    dockerizePip: false
    zip: true
    # 단순하게 모든 라이브러리 포함
    noDeploy: []

package:
  individually: false
  exclude:
    - node_modules/**
    - .venv/**
    - tests/**
    - __pycache__/**
    - "*.pyc"
    - ".pytest_cache/**"
    - ".git/**"
    - "README.md"
    - ".env*"
  include:
    - generate_report.py
    - requirements.txt
