services:
  nginx:
    container_name: backend.proxy
    build: 
      context: .
      dockerfile: proxy.Dockerfile 
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: "/ecomgen/nginx"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "proxy"
        awslogs-create-group: "true"
    networks:
      - shoplingo 

networks:
  shoplingo:
    external: true