services:
  web:
    container_name: web
    image: ${GAR_CONTAINER}
    platform: linux/amd64
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - shoplingo

networks:
  shoplingo:
    external: true
