services:
  web:
    container_name: web
    image: ${GAR_CONTAINER}
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: awslogs
      options:
        awslogs-group: "/ecomgen/backend"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "web"
        awslogs-create-group: "true"
    networks:
      - shoplingo

networks:
  shoplingo:
    external: true