service: ecomgen-infrastructure

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-2
  stage: v1
  profile: cheorish-admin

resources:
  Resources:
    # 텍스트 생성용 SQS 큐 (메시지 보관 14일, 가시성 타임아웃 15분, 롱 폴링 20초, 3회 실패 시 DLQ로 이동)
    TextGenerationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-text-generation-queue
        MessageRetentionPeriod: 1209600  # 14일
        VisibilityTimeout: 900    # 15분 (Lambda timeout과 동일)
        ReceiveMessageWaitTimeSeconds: 20  # Long polling
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt TextGenerationDLQ.Arn
          maxReceiveCount: 3

    # 텍스트 생성 실패 시 이동하는 DLQ (메시지 보관 14일)
    TextGenerationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-text-generation-dlq
        MessageRetentionPeriod: 1209600

    # 이미지 생성용 SQS 큐 (메시지 보관 14일, 가시성 타임아웃 15분, 롱 폴링 20초, 3회 실패 시 DLQ로 이동)
    ImageGenerationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-image-generation-queue
        MessageRetentionPeriod: 1209600  # 14일
        VisibilityTimeout: 900    # 15분 (Lambda timeout과 동일)
        ReceiveMessageWaitTimeSeconds: 20  # Long polling
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ImageGenerationDLQ.Arn
          maxReceiveCount: 3

    # 이미지 생성 실패 시 이동하는 DLQ (메시지 보관 14일)
    ImageGenerationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-image-generation-dlq
        MessageRetentionPeriod: 1209600
    
    # 리포트 생성용 SQS 큐 (메시지 보관 14일, 가시성 타임아웃 15분, 롱 폴링 20초, 3회 실패 시 DLQ로 이동)
    ReportGenerationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-report-generation-queue
        MessageRetentionPeriod: 1209600       # 메시지 보관 기간: 14일
        VisibilityTimeout: 900                # 가시성 타임아웃: 15분 (Lambda 실행 시간과 일치)
        ReceiveMessageWaitTimeSeconds: 20     # 롱 폴링 대기 시간: 20초
        RedrivePolicy:                        # DLQ로 리디렉션되는 조건
          deadLetterTargetArn: !GetAtt ReportGenerationDLQ.Arn
          maxReceiveCount: 3                  # 3회 실패 시 DLQ로 이동

    # 리포트 생성 실패 시 이동하는 DLQ (메시지 보관 14일)
    ReportGenerationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-report-generation-dlq
        MessageRetentionPeriod: 1209600    

  Outputs:
    TextGenerationQueueUrl:
      Description: "텍스트 생성 SQS 큐 URL"
      Value: !Ref TextGenerationQueue
      Export:
        Name: ${self:provider.stage}-TextGenerationQueueUrl

    TextGenerationQueueArn:
      Description: "텍스트 생성 SQS 큐 ARN"
      Value: !GetAtt TextGenerationQueue.Arn
      Export:
        Name: ${self:provider.stage}-TextGenerationQueueArn

    ImageGenerationQueueUrl:
      Description: "이미지 생성 SQS 큐 URL"
      Value: !Ref ImageGenerationQueue
      Export:
        Name: ${self:provider.stage}-ImageGenerationQueueUrl

    ImageGenerationQueueArn:
      Description: "이미지 생성 SQS 큐 ARN"
      Value: !GetAtt ImageGenerationQueue.Arn
      Export:
        Name: ${self:provider.stage}-ImageGenerationQueueArn

    ReportGenerationQueueUrl:
      Description: "리포트 생성 SQS 큐 URL"
      Value: !Ref ReportGenerationQueue
      Export:
        Name: ${self:provider.stage}-ReportGenerationQueueUrl

    ReportGenerationQueueArn:
      Description: "리포트 생성 SQS 큐 ARN"
      Value: !GetAtt ReportGenerationQueue.Arn
      Export:
        Name: ${self:provider.stage}-ReportGenerationQueueArn

    TextDLQUrl:
      Description: "텍스트 생성 DLQ URL"
      Value: !Ref TextGenerationDLQ

    TextDLQArn:
      Description: "텍스트 생성 DLQ ARN"
      Value: !GetAtt TextGenerationDLQ.Arn

    ImageDLQUrl:
      Description: "이미지 생성 DLQ URL"
      Value: !Ref ImageGenerationDLQ

    ImageDLQArn:
      Description: "이미지 생성 DLQ ARN"
      Value: !GetAtt ImageGenerationDLQ.Arn

    ReportDLQUrl:
      Description: "리포트 생성 DLQ URL"
      Value: !Ref ReportGenerationDLQ

    ReportDLQArn:
      Description: "리포트 생성 DLQ ARN"
      Value: !GetAtt ReportGenerationDLQ.Arn
