_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.11.6
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
evaluation_date:
    value: 2025-06-23T11:22:59.555638
sample_size:
    value: 5
