"""Generate to  Member

Revision ID: 0711a6461b36
Revises: 
Create Date: 2025-06-01 18:47:04.058003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0711a6461b36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('product_descriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('generated_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_descriptions_id'), 'product_descriptions', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('input_state', sa.JSON(), nullable=True),
    sa.Column('output_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    op.create_table('showcase_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_description_id', sa.BigInteger(), nullable=False),
    sa.Column('displayed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_description_id'], ['product_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showcase_items_id'), 'showcase_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showcase_items_id'), table_name='showcase_items')
    op.drop_table('showcase_items')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_product_descriptions_id'), table_name='product_descriptions')
    op.drop_table('product_descriptions')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
