"""Report_add column

Revision ID: 33fb7e41aab3
Revises: 20250615_add_job_id
Create Date: 2025-06-18 15:38:44.619562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fb7e41aab3'
down_revision: Union[str, None] = '20250615_add_job_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('web_results', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('job_id', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'job_id')
    op.drop_column('reports', 'web_results')
    op.drop_column('reports', 'content')
    op.drop_column('reports', 'title')
    # ### end Alembic commands ###
