"""Add profile_pic column to members table

Revision ID: 4ece42cf2d1d
Revises: 4e5a158f4fc0
Create Date: 2025-06-13 01:17:53.215997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ece42cf2d1d'
down_revision: Union[str, None] = '4e5a158f4fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('profile_pic', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'profile_pic')
    # ### end Alembic commands ###
