"""remove to run_id

Revision ID: 52c5a39ca339
Revises: 6567b3f6285d
Create Date: 2025-06-18 16:36:46.311673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c5a39ca339'
down_revision: Union[str, None] = '6567b3f6285d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
