"""initial migration reset

Revision ID: 8000cc152e01
Revises: 
Create Date: 2025-06-19 15:43:18.481253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8000cc152e01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.alter_column('members', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product_descriptions', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='user_id::bigint')
    op.create_foreign_key(None, 'product_descriptions', 'members', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_descriptions', type_='foreignkey')
    op.alter_column('product_descriptions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='user_id::varchar')
    op.alter_column('members', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('members', 'provider_id')
    op.drop_column('members', 'provider')
    # ### end Alembic commands ###
