"""add input_prompt and created_at to ProductDescription

Revision ID: a98ddb88348f
Revises: 0711a6461b36
Create Date: 2025-06-09 19:07:27.734738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a98ddb88348f'
down_revision: Union[str, None] = '0711a6461b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'updated_at')
    op.add_column('product_descriptions', sa.Column('input_prompt', sa.Text(), nullable=False))
    op.add_column('product_descriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_descriptions', 'created_at')
    op.drop_column('product_descriptions', 'input_prompt')
    op.add_column('members', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
