# Generated by Django 5.1.7 on 2025-03-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', upload_to='profile_pics/'),
        ),
    ]
